import { base } from '../base';
import { hexToRgb } from '../utils/hexToRgb';

export const button = {
  background: {
    primary: base.palette.product.normal,
    primaryHover: base.palette.product.normalHover,
    primaryActive: base.palette.product.normalActive,
    secondary: base.palette.cloud.normal,
    secondaryHover: base.palette.cloud.normalHover,
    secondaryActive: base.palette.cloud.normalActive,
    info: base.palette.blue.normal,
    infoHover: base.palette.blue.normalHover,
    infoActive: base.palette.blue.normalActive,
    success: base.palette.green.normal,
    successHover: base.palette.green.normalHover,
    successActive: base.palette.green.normalActive,
    warning: base.palette.orange.normal,
    warningHover: base.palette.orange.normalHover,
    warningActive: base.palette.orange.normalActive,
    critical: base.palette.red.normal,
    criticalHover: base.palette.red.normalHover,
    criticalActive: base.palette.red.normalActive,
    white: base.palette.white.normal,
    whiteHover: base.palette.cloud.light,
    whiteActive: base.palette.cloud.lightHover,
    bordered: 'transparent',
    borderedHover: base.palette.cloud.light,
    borderedActive: base.palette.cloud.light,
    whiteBordered: 'transparent',
    whiteBorderedHover: hexToRgb(base.palette.white.normal, 20),
    whiteBorderedActive: hexToRgb(base.palette.white.normal, 20),
    linkPrimary: 'transparent',
    linkPrimaryHover: base.palette.cloud.lightHover,
    linkPrimaryActive: base.palette.cloud.lightActive,
    linkSecondary: 'transparent',
    linkSecondaryHover: base.palette.cloud.lightHover,
    linkSecondaryActive: base.palette.cloud.lightActive,
  },

  border: {
    colors: {
      primary: base.palette.product.normal,
      primaryHover: base.palette.product.normalHover,
      primaryActive: base.palette.product.normalActive,
      secondary: base.palette.ink.normal,
      secondaryHover: base.palette.ink.normalHover,
      secondaryActive: base.palette.ink.normalActive,
      info: base.palette.blue.normal,
      infoHover: base.palette.blue.normalHover,
      infoActive: base.palette.blue.normalActive,
      success: base.palette.green.normal,
      successHover: base.palette.green.normalHover,
      successActive: base.palette.green.normalActive,
      warning: base.palette.orange.normal,
      warningHover: base.palette.orange.normalHover,
      warningActive: base.palette.orange.normalActive,
      critical: base.palette.red.normal,
      criticalHover: base.palette.red.normalHover,
      criticalActive: base.palette.red.normalActive,
      white: base.palette.white.normal,
      whiteHover: base.palette.white.normal,
      whiteActive: base.palette.white.normal,
    },
  },

  fontSize: {
    mini: base.font.size.sm,
    small: base.font.size.sm,
    normal: base.font.size.md,
    large: base.font.size.lg,
  },

  height: {
    mini: base.sizes.sm,
    small: base.sizes.lg,
    normal: base.sizes.xl,
    large: base.sizes.xxl,
  },

  icon: {
    mini: base.sizes.sm,
    small: base.sizes.sm,
    normal: base.sizes.md,
    large: base.sizes.lg,
  },

  margin: {
    icon: {
      mini: base.spacing.xxs,
      small: base.spacing.xs,
      normal: base.spacing.xs,
      large: base.spacing.sm,
    },
    group: {
      default: `0 ${base.spacing.xs} 0 0`,
      connected: '0 1px 0 0',
    },
  },

  opacity: {
    disabled: base.opacity.sm,
  },

  padding: {
    withoutText: '0',
    mini: `0 ${base.spacing.xs}`,
    small: `0 ${base.spacing.sm}`,
    normal: `0 ${base.spacing.md}`,
    large: '0 28px',
    miniWithIcons: `0 ${base.spacing.xxs}`,
    smallWithIcons: `0 ${base.spacing.xs}`,
    normalWithIcons: `0 ${base.spacing.sm}`,
    largeWithIcons: `0 ${base.spacing.md}`,
    miniWithLeftIcon: `0 ${base.spacing.xs} 0 ${base.spacing.xxs}`,
    smallWithLeftIcon: `0 ${base.spacing.sm} 0 ${base.spacing.xs}`,
    normalWithLeftIcon: `0 ${base.spacing.md} 0 ${base.spacing.sm}`,
    largeWithLeftIcon: `0 28px 0 ${base.spacing.md}`,
    miniWithRightIcon: `0 ${base.spacing.xxs} 0 ${base.spacing.xs}`,
    smallWithRightIcon: `0 ${base.spacing.xs} 0 ${base.spacing.sm}`,
    normalWithRightIcon: `0 ${base.spacing.sm} 0 ${base.spacing.md}`,
    largeWithRightIcon: `0 ${base.spacing.md} 0 28px`,
  },

  scale: {
    active: 0.95,
  },

  text: {
    colors: {
      filled: base.palette.white.normal,
      filledHover: base.palette.white.normal,
      filledActive: base.palette.white.normal,
      primary: base.palette.white.normal,
      primaryHover: base.palette.white.normal,
      primaryActive: base.palette.white.normal,
      secondary: base.palette.ink.normal,
      secondaryHover: base.palette.ink.normalHover,
      secondaryActive: base.palette.ink.normalActive,
      info: base.palette.white.normal,
      infoHover: base.palette.white.normal,
      infoActive: base.palette.white.normal,
      success: base.palette.white.normal,
      successHover: base.palette.white.normal,
      successActive: base.palette.white.normal,
      warning: base.palette.white.normal,
      warningHover: base.palette.white.normal,
      warningActive: base.palette.white.normal,
      critical: base.palette.white.normal,
      criticalHover: base.palette.white.normal,
      criticalActive: base.palette.white.normal,
      white: base.palette.ink.normal,
      whiteHover: base.palette.ink.normalHover,
      whiteActive: base.palette.ink.normalActive,
      primaryBordered: base.palette.product.normal,
      primaryBorderedHover: base.palette.product.normalHover,
      primaryBorderedActive: base.palette.product.normalActive,
      secondaryBordered: base.palette.ink.normal,
      secondaryBorderedHover: base.palette.ink.normalHover,
      secondaryBorderedActive: base.palette.ink.normalActive,
      infoBordered: base.palette.blue.normal,
      infoBorderedHover: base.palette.blue.normalHover,
      infoBorderedActive: base.palette.blue.normalActive,
      successBordered: base.palette.green.normal,
      successBorderedHover: base.palette.green.normalHover,
      successBorderedActive: base.palette.green.normalActive,
      warningBordered: base.palette.orange.normal,
      warningBorderedHover: base.palette.orange.normalHover,
      warningBorderedActive: base.palette.orange.normalActive,
      criticalBordered: base.palette.red.normal,
      criticalBorderedHover: base.palette.red.normalHover,
      criticalBorderedActive: base.palette.red.normalActive,
      whiteBordered: base.palette.white.normal,
      whiteBorderedHover: base.palette.white.normal,
      whiteBorderedActive: base.palette.white.normal,
      linkPrimary: base.palette.product.normal,
      linkPrimaryHover: base.palette.product.normalHover,
      linkPrimaryActive: base.palette.product.normalActive,
      linkSecondary: base.palette.ink.normal,
      linkSecondaryHover: base.palette.ink.normalHover,
      linkSecondaryActive: base.palette.ink.normalActive,
    },
  },
};
