import '@fortawesome/fontawesome-svg-core/styles.css';
import { config, library } from '@fortawesome/fontawesome-svg-core';
import { faCommentAlt } from '@fortawesome/free-regular-svg-icons';
import {
  faBars,
  faBell,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faClipboardCheck,
  faCloudDownloadAlt,
  faCogs,
  faEdit,
  faEnvelope,
  faExclamation,
  faExclamationCircle,
  faInfoCircle,
  faLock,
  faMinus,
  faMortarPestle,
  faPlus,
  faSignOutAlt,
  faTimes,
  faTrash,
  faUserCircle,
} from '@fortawesome/free-solid-svg-icons';

config.autoAddCss = false;

library.add(
  faBars,
  faBell,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faClipboardCheck,
  faCloudDownloadAlt,
  faCommentAlt,
  faCogs,
  faEdit,
  faEnvelope,
  faExclamation,
  faExclamationCircle,
  faInfoCircle,
  faLock,
  faMinus,
  faMortarPestle,
  faPlus,
  faSignOutAlt,
  faTrash,
  faTimes,
  faUserCircle,
);
